### ISSUE TITLE
Morality enchantments identifiers

### ISSUE THREAD

**Issue by superbobich** [mome-borogove/40K-enchant-viewer#1]
Would be nice to see if an morality enchant is puritan or radical without having to click on more. Also would be nice to be able to sort them based on puritan or radical it could look sth like this: 

(P) Invulnerability on Kill for 2 seconds (8 seconds cooldown)
meaning that that is a puritan enchant.

**Comment by mome-borogove** [comment]
I implemented something similar which allows filtering by morality.

Only took a year. ;)
