### ISSUE TITLE
any i18n support?

### ISSUE THREAD

**Issue by mela93** [mome-borogove/40K-enchant-viewer#4]

**Comment by mela93** [comment]
Is there any development process?

**Comment by mome-borogove** [comment]
A belated response, but no, I haven't really considered international support. There's two reasons for this. The first is simply the amount of effort supporting all the different languages that Inquisitor supports---it's a lot. The second is actually more of a problem: the non-English localization strings inside the game are not as well supported. This means that a lot of the time, the strings in non-English languages are actually incorrect. While this is kind of a disservice to international players, there's not a lot I can do about that. Sorry!
