### ISSUE TITLE
Selected Item-specific filters don't clear by using the Clear button

### ISSUE THREAD

**Issue by Psojed** [mome-borogove/40K-enchant-viewer#9]
1) Pick a slot in the slotmap, for example **Weapon** slot.
2) Select any Item-Specific filter, ie. **Aether Blade**. We now see enchants only available on that specific item.
3) Click the **Clear** button in the slotmap.
4) Pick a different slot in the slotmap, for example **Body Armor**.

The filter will still list enchants available for the Aether Blade.

**Comment by mome-borogove** [comment]
Thanks for the report!
